version: "3.3"

services:
  employee-api:
    build:
      dockerfile: .Dockerfile
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    command: ./manage.py runserver
  postgres:
    image: bitnami/postgresql:14.10.0-debian-11-r17
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: omnihr
    ports:
      - "127.0.0.1:15432:5432"
    command: "-c fsync=off -c synchronous_commit=off -c full_page_writes=off -c random_page_cost=1.0"
  redis:
    image: redis:4.0
    environment:
      ALLOW_EMPTY_PASSWORD: yes
    ports:
      - "127.0.0.1:16379:6379"