version: "3.3"

services:
  postgres:
    image: bitnami/postgresql:14.10.0-debian-11-r17
    environment:
      POSTGRES_DB: omnihr
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    volumes:
      - ./tmp:/data
    ports:
      - "127.0.0.1:15432:5432"
  redis:
    image: bitnami/redis
    environment:
      ALLOW_EMPTY_PASSWORD: yes
    ports:
      - "127.0.0.1:16379:6379"